"""Añadir nuevos campos a la tabla Turno

Revision ID: 0b372a41fd3e
Revises: b96ccf2b7d15
Create Date: 2024-11-14 13:45:16.121629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b372a41fd3e'
down_revision = 'b96ccf2b7d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Data_Turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('motivo', sa.String(length=100), nullable=False))
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Data_Turnos', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('motivo')
        batch_op.drop_column('cedula')

    # ### end Alembic commands ###
