"""empty message

Revision ID: 4f80383c1fd2
Revises: 0b372a41fd3e
Create Date: 2024-11-14 16:14:01.740995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f80383c1fd2'
down_revision = '0b372a41fd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Data_Turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_turno_regional', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('contador_pago_deuda', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ganador', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Data_Turnos', schema=None) as batch_op:
        batch_op.drop_column('ganador')
        batch_op.drop_column('contador_pago_deuda')
        batch_op.drop_column('numero_turno_regional')

    # ### end Alembic commands ###
